<?php

namespace Database\Seeders;

use App\Models\District;
use App\Models\Thana;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Thana::truncate();
        District::truncate();

        $data = [
            'Bagerhat' => [
                'Bagerhat Sadar',
                'Chitalmari',
                'Fakirhat',
                'Kachua',
                'Mollahat',
                'Mongla',
                'Morrelganj',
                'Rampal',
                'Sarankhola',
            ],
            'Bandarban' => [
                'Bandarban Sadar',
                'Lama',
                'Rowangchhari',
                'Ruma',
                'Thanchi',
            ],
            'Barguna' => [
                'Amtali',
                'Bamna',
                'Barguna Sadar',
                'Betagi',
                'Patharghata',
            ],
            'Barishal' => [
                'Agailjhara',
                'Babuganj',
                'Bakerganj',
                'Banaripara',
                'Barishal Sadar',
                'Gaurnadi',
                'Hizla',
                'Mehendiganj',
                'Muladi',
                'Wazirpur',
            ],
            'Bhola' => [
                'Bhola Sadar',
                'Borhanuddin',
                'Char Fasson',
                'Daulatkhan',
                'Lalmohan',
                'Manpura',
                'Tazumuddin',
            ],
            'Bogra' => [
                'Adamdighi',
                'Bogra Sadar',
                'Dhunat',
                'Dhupchanchia',
                'Gabtali',
                'Kahaloo',
                'Nandigram',
                'Sariakandi',
                'Shajahanpur',
                'Sherpur',
                'Shibganj',
                'Sonatala',
            ],
            'Brahmanbaria' => [
                'Akhaura',
                'Bancharampur',
                'Brahmanbaria Sadar',
                'Kasba',
                'Nabinagar',
                'Nasirnagar',
                'Sarail',
            ],
            'Chandpur' => [
                'Chandpur Sadar',
                'Faridganj',
                'Haimchar',
                'Haziganj',
                'Kachua',
                'Matlab Dakshin',
                'Matlab Uttar',
            ],
            'Chapainawabganj' => [
                'Bholahat',
                'Chapainawabganj Sadar',
                'Gomastapur',
                'Nachole',
                'Nawabganj',
                'Shibganj',
            ],
            'Chattogram' => [
                'Anwara',
                'Banshkhali',
                'Boalkhali',
                'Chattogram Sadar',
                'Fatikchhari',
                'Hathazari',
                'Lohagara',
                'Mirsharai',
                'Patiya',
                'Rangunia',
                'Raozan',
                'Sandwip',
                'Satkania',
                'Sitakunda',
            ],
            'Chuadanga' => [
                'Alamdanga',
                'Chuadanga Sadar',
                'Damurhuda',
                'Jibannagar',
            ],
            'Comilla' => [
                'Barura',
                'Brahmanpara',
                'Burichang',
                'Chandina',
                'Chauddagram',
                'Comilla Sadar Dakshin',
                'Comilla Sadar Uttar',
                'Daudkandi',
                'Debidwar',
                'Homna',
                'Laksam',
                'Monohargonj',
                'Nangalkot',
                'Titas',
            ],
            'Cox\'s Bazar' => [
                'Chakaria',
                'Cox\'s Bazar Sadar',
                'Kutubdia',
                'Maheshkhali',
                'Ramu',
                'Teknaf',
                'Ukhia',
            ],
            'Dhaka' => [
                'Adabor',
                'Badda',
                'Bangshal',
                'Bimanbandar',
                'Cantonment',
                'Chak Bazar',
                'Darus Salam',
                'Demra',
                'Dhamrai',
                'Dhanmondi',
                'Gendaria',
                'Gulshan',
                'Hazaribagh',
                'Jatrabari',
                'Kadamtali',
                'Kafrul',
                'Kalabagan',
                'Kamrangirchar',
                'Keraniganj',
                'Khilgaon',
                'Khilkhet',
                'Kotwali',
                'Lalbagh',
                'Mirpur',
                'Mohammadpur',
                'Motijheel',
                'Nawabganj',
                'Pallabi',
                'Paltan',
                'Ramna',
                'Rampura',
                'Sabujbagh',
                'Shah Ali',
                'Shahbagh',
                'Sher-e-Bangla Nagar',
                'Shyampur',
                'Sutrapur',
                'Tejgaon',
                'Turag',
                'Uttar Khan',
            ],
            'Dinajpur' => [
                'Birampur',
                'Birganj',
                'Biral',
                'Bochaganj',
                'Chirirbandar',
                'Phulbari',
                'Ghoraghat',
                'Hakimpur',
                'Kaharole',
                'Khansama',
                'Dinajpur Sadar',
                'Nawabganj',
                'Parbatipur',
            ],
            'Faridpur' => [
                'Alfadanga',
                'Bhanga',
                'Boalmari',
                'Charbhadrasan',
                'Faridpur Sadar',
                'Madhukhali',
                'Nagarkanda',
                'Sadarpur',
            ],
            'Feni' => [
                'Chhagalnaiya',
                'Daganbhuiyan',
                'Feni Sadar',
                'Parshuram',
                'Sonagazi',
            ],
            'Gaibandha' => [
                'Bonarpara',
                'Fulchhari',
                'Gaibandha Sadar',
                'Gobindaganj',
                'Palashbari',
                'Sadullapur',
                'Sughat',
            ],
            'Gazipur' => [
                'Gazipur Sadar',
                'Kaliakair',
                'Kaliganj',
                'Kapasia',
                'Sreepur',
            ],
            'Gopalganj' => [
                'Gopalganj Sadar',
                'Kashiani',
                'Kotalipara',
                'Madaripur Sadar',
                'Rajoir',
            ],
            'Habiganj' => [
                'Ajmiriganj',
                'Baniachang',
                'Bahubal',
                'Chunarughat',
                'Habiganj Sadar',
                'Lakhai',
                'Madhabpur',
                'Nabiganj',
            ],
            'Jamalpur' => [
                'Baksiganj',
                'Dewanganj',
                'Islampur',
                'Jamalpur Sadar',
                'Melandaha',
                'Sarishabari',
                'Sharishabari',
            ],
            'Jashore' => [
                'Abhaynagar',
                'Bagherpara',
                'Chaugachha',
                'Jhikargachha',
                'Jashore Sadar',
                'Keshabpur',
                'Manirampur',
                'Sarsha',
            ],
            'Jhalokathi' => [
                'Jhalokathi Sadar',
                'Kathalia',
                'Nalchity',
                'Rajapur',
            ],
            'Jhenaidah' => [
                'Harinakundu',
                'Jhenaidah Sadar',
                'Kaliganj',
                'Kotchandpur',
                'Maheshpur',
                'Shailkupa',
            ],
            'Joypurhat' => [
                'Akkelpur',
                'Joypurhat Sadar',
                'Kalai',
                'Khetlal',
                'Panchbibi',
            ],
            'Khagrachari' => [
                'Dighinala',
                'Khagrachari Sadar',
                'Laxmichhari',
                'Mahalchhari',
                'Manikchhari',
                'Matiranga',
                'Panchhari',
                'Ramgarh',
            ],
            'Khulna' => [
                'Batiaghata',
                'Dacope',
                'Dighalia',
                'Koyra',
                'Paikgachha',
                'Phultala',
                'Rupsha',
                'Terokhada',
            ],
            'Kishoreganj' => [
                'Austagram',
                'Bajitpur',
                'Bhairab',
                'Hossainpur',
                'Itna',
                'Karimganj',
                'Katiadi',
                'Kishoreganj Sadar',
                'Kuliarchar',
                'Mithamain',
                'Nikli',
                'Pakundia',
                'Tarail',
            ],
            'Kurigram' => [
                'Bhurungamari',
                'Char Rajibpur',
                'Chilmari',
                'Kurigram Sadar',
                'Nageshwari',
                'Phulbari',
                'Raomari',
                'Rowmari',
                'Ulipur',
            ],
            'Kushtia' => [
                'Bheramara',
                'Daulatpur',
                'Khoksa',
                'Kumarkhali',
                'Kushtia Sadar',
                'Mirpur',
            ],
            'Lakshmipur' => [
                'Lakshmipur Sadar',
                'Ramganj',
                'Raipur',
                'Ramgati',
            ],
            'Lalmonirhat' => [
                'Aditmari',
                'Hatibandha',
                'Kaliganj',
                'Lalmonirhat Sadar',
                'Patgram',
            ],
            'Madaripur' => [
                'Barishal',
                'Kalkini',
                'Madaripur Sadar',
                'Rajoir',
            ],
            'Magura' => [
                'Magura Sadar',
                'Mohammadpur',
                'Shalikha',
                'Sreepur',
            ],
            'Manikganj' => [
                'Daulatpur',
                'Gheor',
                'Harirampur',
                'Manikganj Sadar',
                'Saturia',
                'Shibaloy',
            ],
            'Meherpur' => [
                'Gangni',
                'Mujibnagar',
                'Meherpur Sadar',
            ],
            'Moulvibazar' => [
                'Barlekha',
                'Juri',
                'Kamalganj',
                'Kulaura',
                'Moulvibazar Sadar',
                'Rajnagar',
                'Sreemangal',
            ],
            'Munshiganj' => [
                'Gazaria',
                'Lohajang',
                'Munshiganj Sadar',
                'Sirajdikhan',
                'Tongibari',
            ],
            'Mymensingh' => [
                'Bhaluka',
                'Dhobaura',
                'Fulbaria',
                'Gafargaon',
                'Gauripur',
                'Haluaghat',
                'Ishwarganj',
                'Muktagachha',
                'Mymensingh Sadar',
                'Nandail',
                'Phulpur',
                'Trishal',
            ],
            'Naogaon' => [
                'Atrai',
                'Badalgachhi',
                'Dhamoirhat',
                'Manda',
                'Mohadevpur',
                'Naogaon Sadar',
                'Niamatpur',
                'Patnitala',
                'Porsha',
                'Raninagar',
                'Sapahar',
            ],
            'Narail' => [
                'Kalia',
                'Lohagara',
                'Narail Sadar',
            ],
            'Narayanganj' => [
                'Araihazar',
                'Baidder Bazar',
                'Bandar',
                'Narayanganj Sadar',
                'Rupganj',
                'Siddhirganj',
                'Sonargaon',
            ],
            'Narsingdi' => [
                'Belabo',
                'Monohardi',
                'Narsingdi Sadar',
                'Palash',
                'Raipura',
                'Shibpur',
            ],
            'Natore' => [
                'Bagatipara',
                'Baraigram',
                'Gurudaspur',
                'Lalpur',
                'Natore Sadar',
                'Singra',
            ],
            'Nawabganj' => [
                'Bholahat',
                'Gomastapur',
                'Nachole',
                'Nawabganj Sadar',
                'Shibganj',
            ],
            'Netrokona' => [
                'Atpara',
                'Barhatta',
                'Durgapur',
                'Khaliajuri',
                'Kalmakanda',
                'Kendua',
                'Madan',
                'Netrokona Sadar',
                'Purbadhala',
                'Kurigram',
                'Raomari',
                'Ulipur',
            ],
            'Nilphamari' => [
                'Dimla',
                'Domar',
                'Jaldhaka',
                'Kishoreganj',
                'Nilphamari Sadar',
                'Saidpur',
            ],
            'Pabna' => [
                'Atgharia',
                'Bera',
                'Bhangura',
                'Chatmohar',
                'Faridpur',
                'Ishwardi',
                'Pabna Sadar',
                'Santhia',
                'Sujanagar',
            ],
            'Panchagarh' => [
                'Atwari',
                'Boda',
                'Debiganj',
                'Panchagarh Sadar',
                'Tetulia',
            ],
            'Patuakhali' => [
                'Bauphal',
                'Dashmina',
                'Galachipa',
                'Kalapara',
                'Mirzaganj',
                'Patuakhali Sadar',
            ],
            'Pirojpur' => [
                'Bhandaria',
                'Kaukhali',
                'Mathbaria',
                'Nazirpur',
                'Pirojpur Sadar',
            ],
            'Rajbari' => [
                'Baliakandi',
                'Goalandaghat',
                'Pangsha',
                'Rajbari Sadar',
                'Kalukhali',
            ],
            'Rajshahi' => [
                'Bagha',
                'Bagmara',
                'Charghat',
                'Durgapur',
                'Godagari',
                'Mohonpur',
                'Paba',
                'Puthia',
                'Rajpara',
                'Tanore',
            ],
            'Rangamati' => [
                'Baghaichari',
                'Barkal',
                'Kawkhali',
                'Langadu',
                'Naniarchar',
                'Rajasthali',
                'Rangamati Sadar',
            ],
            'Rangpur' => [
                'Badarganj',
                'Gangachara',
                'Kaunia',
                'Mithapukur',
                'Pirganj',
                'Rangpur Sadar',
                'Taraganj',
            ],
            'Satkhira' => [
                'Assasuni',
                'Debhata',
                'Kaliganj',
                'Kolaroa',
                'Satkhira Sadar',
                'Shyamnagar',
                'Tala',
            ],
            'Shariatpur' => [
                'Bhedarganj',
                'Damudya',
                'Gosairhat',
                'Naria',
                'Shariatpur Sadar',
                'Zajira',
            ],
            'Sherpur' => [
                'Jhenaigati',
                'Nakla',
                'Nalitabari',
                'Sherpur Sadar',
                'Sreebardi',
            ],
            'Sirajganj' => [
                'Belkuchi',
                'Chauhali',
                'Kamarkhand',
                'Kazipur',
                'Raiganj',
                'Shahjadpur',
                'Sirajganj Sadar',
                'Tarash',
                'Ullapara',
            ],
            'Sunamganj' => [
                'Bishwamvarpur',
                'Chhatak',
                'Dakshin Sunamganj',
                'Dharampasha',
                'Jagannathpur',
                'Jamalganj',
                'Sachna',
                'Shalla',
                'Sunamganj',
                'Tahirpur',
            ],
            'Sylhet' => [
                'Beanibazar',
                'Bishwanath',
                'Companiganj',
                'Dakshin Surma',
                'Fenchuganj',
                'Golapganj',
                'Gowainghat',
                'Jaintiapur',
                'Kanaighat',
                'Zakiganj',
            ],
            'Tangail' => [
                'Basail',
                'Delduar',
                'Ghatail',
                'Gopalpur',
                'Kalihati',
                'Madhupur',
                'Mirzapur',
                'Nagarpur',
                'Sakhipur',
                'Tangail Sadar',
            ],
            'Thakurgaon' => [
                'Baliadangi',
                'Haripur',
                'Pirganj',
                'Ranisankail',
                'Thakurgaon Sadar',
            ],
        ];

        DB::transaction(fn () => collect($data)->each(function ($thanas, $district) {
            District::create(['name' => $district])->thanas()->createMany(
                array_map(fn ($thana) => ['name' => $thana], $thanas)
            );
        }));
    }
}
